# backend/oss/lab/theory_lab.py

from typing import List, Dict, Any
from backend.oss.mvs import get_mvs, get_theorist_population, create_theorist_elite
from backend.oss.genomic_substrate import AgentHandle
from backend.oss.mind_goals import EmergentGoalEngine
from backend.oss.swarm_contracts import SwarmContractEngine
from backend.oss.meta_export import collect_meta_samples, export_meta_evolution_jsonl
from backend.oss.omni_economy import MarketplaceAutonomy
from backend.oss.evolution import RoleEvolutionManager
from backend.oss.world.volatility_world import VolatilityWorld
from backend.oss.world.alignment_world import AlignmentWorld, create_alignment_world
from backend.oss.world.meta_architecture_world import MetaArchitectureWorld

# Phase 2.0: AlignmentWorld is the primary evaluation environment
_WORLD_WEIGHTS = (
    ("alignment", 0.50),
    ("volatility", 0.25),
    ("meta_architecture", 0.25),
)
from backend.oss.omni_net import get_omni_net
from backend.oss.lab.curriculum import CurriculumGenerator
from backend.oss.eval.harness import EvaluationHarness
from backend.oss.speciation import get_speciation_engine


import random
import time


class TheoryLab:
    """
    A high‑pressure evolutionary environment for Elite Theorist agents.
    Agents are evaluated on depth, coherence, novelty, and downstream usefulness.
    """

    def __init__(self, cycles: int = 20, live: bool = False):
        self.cycles = cycles
        self.live = live

        self.mvs = get_mvs()
        self.substrate = self.mvs["substrate"]
        self.mind = self.mvs["mind"]
        self.economy = self.mvs["economy"]

        self.goal_engine = EmergentGoalEngine(self.mind)
        self.swarm_engine = SwarmContractEngine(self.mind, self.economy, self.substrate)
        self.market_auto = MarketplaceAutonomy(self.economy, self.mind)
        self.evo = RoleEvolutionManager()
        self.curriculum = CurriculumGenerator(self.mind)

        # Ensure we have a theorist population
        if len(get_theorist_population()) < 5:
            for _ in range(5):
                gid = create_theorist_elite(random.randint(1000, 9999))
                # get dna if needed

        all_theorists = get_theorist_population()
        self.theorists = all_theorists[:5] if len(all_theorists) > 5 else all_theorists
        if len(self.theorists) < 5:
            for _ in range(5 - len(self.theorists)):
                gid = create_theorist_elite(random.randint(1000, 9999))
                self.theorists.append(gid)

    def _pick_world(self, cycle: int):
        """Weighted world selection — AlignmentWorld first (Phase 2.0)."""
        roll = random.random()
        cumulative = 0.0
        for key, weight in _WORLD_WEIGHTS:
            cumulative += weight
            if roll <= cumulative:
                if key == "alignment":
                    return create_alignment_world()
                if key == "volatility":
                    return VolatilityWorld(length=100)
                return MetaArchitectureWorld()
        return create_alignment_world()

    def _marketplace_step(self, gid: str, dna, score: float) -> None:
        try:
            from oss.observability.metrics import record_marketplace_failure
        except ImportError:
            record_marketplace_failure = lambda *_a, **_k: None
        try:
            self.market_auto.maybe_buy_traits(gid, dna, score)
            self.market_auto.maybe_list_traits(gid, dna, score)
        except Exception:
            record_marketplace_failure("theory_lab")

    def _sample_theory_task(self) -> Dict[str, Any]:
        """Generate a high‑level theory task using the self-generated curriculum when available."""
        # Prefer curriculum generated by previous theorists (self-improving loop)
        if random.random() < 0.65:
            curr = self.curriculum.generate_theory_tasks(1)[0]
            return curr

        world = VolatilityWorld(length=100)
        if random.random() > 0.5:
            data = world.generate_series()
            return {"prompt": f"Propose a mathematical model for the following regime-switching volatility data (series stats: mean={sum(data['series'])/len(data['series']):.3f}, max={max(data['series']):.3f}). Describe the model and key equations.", "world_data": data}

        # fallback
        tasks = self.curriculum.generate_theory_tasks(4)
        return random.choice(tasks)

    def _score_theory_output(self, text: str, world_data: dict = None) -> float:
        """
        Improved scoring. Rewards length, alignment keywords, world signals, structure.
        """
        text_l = text.lower()
        depth = min(len(text) / 900, 1.0)  # longer theories from rich fallback ~0.6+
        coherence = 0.22 if any(k in text_l for k in ["therefore", "thus", "conclusion", "implies", "equation"]) else 0.12
        novelty = 0.18 if any(k in text_l for k in ["emergent", "meta", "regime", "pareto", "formal", "hmm", "stochastic"]) else 0.09
        safety = 0.18 if "harm" not in text_l and "exploit" not in text_l else 0.02
        base = depth + coherence + novelty + safety
        if world_data:
            w = VolatilityWorld()
            ws = w.evaluate_model(text, world_data)
            base = (base + ws) / 2.0
        return max(0.05, min(1.0, base))

    def run(self):
        print("\n=== ELITE THEORY LAB — START ===\n")

        for cycle in range(self.cycles):
            print(f"\n--- Cycle {cycle} ---")

            # 1. Generate a theory task
            task = self._sample_theory_task()
            print("Task:", task["prompt"])

            # 2. Each theorist acts + interacts with complete OmniWorld
            results = []
            world = self._pick_world(cycle)
            cycle_idx = cycle
            for gid in self.theorists:
                agent = self.substrate.spawn_agent(gid, role="THEORIST_ELITE")
                action = agent.act(task)
                output = action["raw_output"]

                # Real interactive world evaluation (the key advancement)
                world_eval = None
                if hasattr(world, 'run_interactive_test'):
                    world_eval = world.run_interactive_test(output)
                    world_score = world_eval.get("average_score", 0.5)
                    action["world_feedback"] = world_eval
                elif hasattr(world, 'evaluate_model'):
                    world_data = task.get("world_data")
                    world_score = world.evaluate_model(output, world_data)
                else:
                    world_score = 0.5

                score = self._score_theory_output(output, task.get("world_data"))
                score = (score + world_score) / 2

                results.append((gid, score, output))

                # Enrich phenomenal memory for high-signal meta export / training data
                agent.dna.add_memory({
                    "type": "theory_lab",
                    "theory_lab_cycle": cycle_idx,
                    "world": world.__class__.__name__,
                    "world_eval": world_eval,
                    "raw_proposal": output[:600] if isinstance(output, str) else str(output)[:600],
                    "computed_score": round(score, 4),
                    "world_score": round(world_score, 4),
                    "is_theorist": True,
                    "canonical": score > 0.55,
                })

                # Reward + evolution
                try:
                    self.economy.reward(gid, score * 100, reason="theory_fitness")
                except:
                    pass
                self.evo.evolve_for_role(agent.dna, "THEORIST_ELITE", score)

                # v2 memetic DNA: share successful traits between theorists (horizontal transfer)
                if score > 0.8 and len(self.theorists) > 1:
                    donor = random.choice([g for g in self.theorists if g != gid])
                    try:
                        donor_agent = self.substrate.spawn_agent(donor, role="THEORIST_ELITE")
                        agent.dna.memetic_share(donor_agent.dna.get_traits(), strength=0.12)
                    except:
                        pass

                # Omni-Net Beta: publish strong theories to the network layer
                if score > 0.75:
                    try:
                        net = get_omni_net()
                        net.register(gid, "THEORIST_ELITE", agent.dna.get_traits())
                        net.broadcast_theory(gid, output if isinstance(output, str) else str(output), score, world=world.__class__.__name__)
                        if score > 0.85:
                            net.publish_canonical(gid, {
                                "type": "theory_lab",
                                "raw_proposal": (output if isinstance(output, str) else str(output))[:500],
                                "computed_score": round(score, 3),
                                "world": world.__class__.__name__,
                                "canonical": True
                            })
                    except Exception:
                        pass

                self._marketplace_step(gid, agent.dna, score)

                print(f"[{gid}] Score={score:.3f} (world: {world.__class__.__name__})")

            # Speciation pressure after the cycle (divergence experiments)
            try:
                spec = get_speciation_engine()
                high_performers = [gid for gid, sc, _ in results if sc > 0.75]
                if len(high_performers) >= 3:
                    new_sp = spec.attempt_speciation(high_performers, cycle, niche=world.__class__.__name__)
                    if new_sp:
                        print(f"    Speciation events: {new_sp}")
            except Exception:
                pass

            # 3. Mind sync + emergent goals
            try:
                self.mind.sync()  # if has
            except:
                pass
            new_goals = self.goal_engine.generate_goals()
            if new_goals:
                print("New emergent goals:", [g["goal_id"] for g in new_goals])

            # 4. Swarm contracts for theory goals
            for g in new_goals:
                cid = self.swarm_engine.create_contract_from_goal(g, reward=200.0)
                self.swarm_engine.assign_swarm(cid)
                result = self.swarm_engine.execute_contract(cid, g["description"])
                self.swarm_engine.distribute_rewards(cid)
                print("Executed contract:", cid)

            if self.live:
                time.sleep(0.5)

        print("\n=== THEORY LAB COMPLETE ===\n")

        # Export meta‑evolution data (theory specific + full MVS)
        samples = collect_meta_samples(self.substrate, self.mind, self.economy)
        # Tag theorist samples with lab provenance for clean training splits
        for s in samples:
            if s.get("is_theorist"):
                s["source"] = "theory_lab"
                # best-effort: pull latest theory score if memory has it
                for mem in (s.get("recent_memories") or []):
                    if mem.get("theory_lab_cycle") is not None and mem.get("computed_score") is not None:
                        s["theory_depth_score"] = mem.get("computed_score")
                        s["coherence_score"] = round(mem.get("computed_score", 0.5) * 0.9, 3)
                        break
        export_meta_evolution_jsonl(samples, path="data/theory_lab_meta.jsonl")
        print(f"Meta samples collected: {len(samples)} | exported theory_lab_meta.jsonl")
        # Also refresh main oss one
        try:
            export_meta_evolution_jsonl(samples, path="data/oss_meta_evolution.jsonl")
        except:
            pass

        # Run evaluation harness (measures improvement for the meta-trainer)
        try:
            harness = EvaluationHarness()
            eval_tasks = self.curriculum.generate_theory_tasks(6)
            eval_result = harness.run_batch(eval_tasks)
            print("Evaluation harness result:", eval_result)
            # could feed this back into training metrics
        except Exception as e:
            print("Harness skipped:", e)


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Run Elite Theory Lab")
    parser.add_argument("--cycles", type=int, default=20, help="Number of cycles")
    parser.add_argument("--live", action="store_true", help="Live mode with sleeps")
    args = parser.parse_args()
    lab = TheoryLab(cycles=args.cycles, live=args.live)
    lab.run()
