"""Fix cell 9 (training cell) — write source as proper list of lines with real \n escapes."""
import json
from pathlib import Path

nb_path = Path('C:/Users/leer4/GH05T3/kaggle_train.ipynb')
nb = json.loads(nb_path.read_text(encoding='utf-8'))

# Write source as a list of properly-escaped lines
new_source = [
    "# -- 7. Format + train --------------------------------------------------------\n",
    "import torch\n",
    "from transformers import TrainingArguments\n",
    "\n",
    "def _wrap(goal):\n",
    "    return (\n",
    "        '<|im_start|>system\\n' + SYSTEM + '<|im_end|>\\n'\n",
    "        '<|im_start|>user\\n' + str(goal) + '<|im_end|>\\n'\n",
    "        '<|im_start|>assistant\\n'\n",
    "    )\n",
    "\n",
    "# BF16 support detection (T4 = False, A100 = True)\n",
    "if BACKEND == 'cuda':\n",
    "    USE_BF16 = torch.cuda.is_bf16_supported()\n",
    "    USE_FP16 = not USE_BF16\n",
    "else:\n",
    "    USE_BF16 = False\n",
    "    USE_FP16 = False\n",
    "\n",
    "print(f'Using BF16={USE_BF16}  FP16={USE_FP16}')\n",
    "\n",
    "if MODE == 'sft':\n",
    "    from trl import SFTTrainer, SFTConfig\n",
    "\n",
    "    def fmt(row):\n",
    "        g = str(row.get('instruction') or row.get('goal') or row.get('prompt') or '')\n",
    "        r = str(row.get('response') or row.get('chosen') or '')\n",
    "        return {'text': _wrap(g) + r + '<|im_end|>'}\n",
    "\n",
    "    ds_fmt = ds.map(fmt, remove_columns=ds.column_names)\n",
    "    trainer = SFTTrainer(\n",
    "        model=model, tokenizer=tokenizer,\n",
    "        train_dataset=ds_fmt,\n",
    "        args=SFTConfig(\n",
    "            dataset_text_field='text',\n",
    "            max_seq_length=MAX_SEQ,\n",
    "            packing=False,\n",
    "            per_device_train_batch_size=2, gradient_accumulation_steps=4,\n",
    "            num_train_epochs=EPOCHS, learning_rate=2e-4,\n",
    "            bf16=USE_BF16, fp16=USE_FP16, logging_steps=10,\n",
    "            output_dir=OUTPUT_DIR, warmup_ratio=0.1,\n",
    "            lr_scheduler_type='cosine', save_strategy='epoch', report_to='none',\n",
    "            gradient_checkpointing=True,\n",
    "            gradient_checkpointing_kwargs={'use_reentrant': False},\n",
    "            dataloader_pin_memory=False,\n",
    "        ),\n",
    "    )\n",
    "\n",
    "elif MODE == 'orpo':\n",
    "    from trl import ORPOTrainer, ORPOConfig\n",
    "\n",
    "    def fmt_orpo(row):\n",
    "        g = str(row.get('goal') or row.get('instruction') or '')\n",
    "        p = str(row.get('prompt') or ('GOAL: ' + g + '\\n\\nProvide a detailed sovereign response:'))\n",
    "        return {\n",
    "            'prompt':   _wrap(p),\n",
    "            'chosen':   str(row['chosen']) + '<|im_end|>',\n",
    "            'rejected': str(row['rejected']) + '<|im_end|>',\n",
    "        }\n",
    "\n",
    "    ds_fmt = ds.map(fmt_orpo, remove_columns=ds.column_names)\n",
    "    trainer = ORPOTrainer(\n",
    "        model=model, tokenizer=tokenizer, train_dataset=ds_fmt,\n",
    "        args=ORPOConfig(\n",
    "            max_length=MAX_SEQ, max_prompt_length=512, beta=0.1,\n",
    "            per_device_train_batch_size=1, gradient_accumulation_steps=8,\n",
    "            num_train_epochs=EPOCHS, learning_rate=8e-6,\n",
    "            bf16=USE_BF16, fp16=USE_FP16, logging_steps=10,\n",
    "            output_dir=OUTPUT_DIR, warmup_ratio=0.1,\n",
    "            lr_scheduler_type='cosine', save_strategy='epoch', report_to='none',\n",
    "        ),\n",
    "    )\n",
    "\n",
    "elif MODE == 'dpo':\n",
    "    from trl import DPOTrainer, DPOConfig\n",
    "\n",
    "    def fmt_dpo(row):\n",
    "        g = str(row.get('goal') or row.get('instruction') or '')\n",
    "        p = str(row.get('prompt') or ('GOAL: ' + g + '\\n\\nProvide a detailed sovereign response:'))\n",
    "        return {\n",
    "            'prompt':   _wrap(p),\n",
    "            'chosen':   str(row['chosen']) + '<|im_end|>',\n",
    "            'rejected': str(row['rejected']) + '<|im_end|>',\n",
    "        }\n",
    "\n",
    "    ds_fmt = ds.map(fmt_dpo, remove_columns=ds.column_names)\n",
    "    trainer = DPOTrainer(\n",
    "        model=model, ref_model=None, tokenizer=tokenizer, train_dataset=ds_fmt,\n",
    "        args=DPOConfig(\n",
    "            max_length=MAX_SEQ, max_prompt_length=512, beta=0.1,\n",
    "            per_device_train_batch_size=1, gradient_accumulation_steps=8,\n",
    "            num_train_epochs=EPOCHS, learning_rate=5e-6,\n",
    "            bf16=USE_BF16, fp16=USE_FP16, logging_steps=10,\n",
    "            output_dir=OUTPUT_DIR, warmup_ratio=0.1,\n",
    "            lr_scheduler_type='cosine', save_strategy='epoch', report_to='none',\n",
    "        ),\n",
    "    )\n",
    "\n",
    "elif MODE == 'grpo':\n",
    "    from trl import GRPOTrainer, GRPOConfig\n",
    "\n",
    "    def _reward(completions, **kwargs):\n",
    "        scores = []\n",
    "        for text in completions:\n",
    "            s = 0.0\n",
    "            if len(text) > 400: s += 1.0\n",
    "            elif len(text) > 150: s += 0.5\n",
    "            else: s -= 0.5\n",
    "            if text.count('\\n') > 3: s += 0.5\n",
    "            scores.append(s)\n",
    "        return scores\n",
    "\n",
    "    def fmt_grpo(row):\n",
    "        p = str(row.get('prompt') or row.get('instruction') or row.get('goal') or '')\n",
    "        return {'prompt': _wrap(p)}\n",
    "\n",
    "    ds_fmt = ds.map(fmt_grpo, remove_columns=ds.column_names)\n",
    "    ds_fmt = ds_fmt.filter(lambda r: len(r['prompt']) > 20)\n",
    "    trainer = GRPOTrainer(\n",
    "        model=model, tokenizer=tokenizer, train_dataset=ds_fmt,\n",
    "        reward_funcs=[_reward],\n",
    "        args=GRPOConfig(\n",
    "            max_prompt_length=512, max_completion_length=512, num_generations=4,\n",
    "            per_device_train_batch_size=1, gradient_accumulation_steps=8,\n",
    "            num_train_epochs=EPOCHS, learning_rate=5e-6,\n",
    "            bf16=USE_BF16, fp16=USE_FP16, logging_steps=10,\n",
    "            output_dir=OUTPUT_DIR, warmup_ratio=0.1,\n",
    "            lr_scheduler_type='cosine', save_strategy='epoch', report_to='none',\n",
    "        ),\n",
    "    )\n",
    "\n",
    "print(f'Starting: {MODE.upper()}  agent={AGENT}  {len(ds_fmt)} examples...')\n",
    "stats = trainer.train()\n",
    "loss  = stats.metrics.get('train_loss', 0)\n",
    "rt    = stats.metrics.get('train_runtime', 0)\n",
    "print(f'Training complete!  Loss={loss:.4f}  Time={rt/60:.1f} min')\n",
]

nb['cells'][9]['source'] = new_source
nb_path.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding='utf-8')
print(f'Cell 9 fixed. Total lines: {len(new_source)}')

# Quick syntax check
import ast
src = ''.join(new_source)
try:
    ast.parse(src)
    print('Syntax check: PASS')
except SyntaxError as e:
    print(f'Syntax check: FAIL — {e}')
