"""KAIROS → GitHub auto-PR creator.

When SAGE produces an elite proposal (score ≥ 0.90), this module creates a
draft GitHub PR with an implementation skeleton so the idea doesn't just sit
in the archive — it becomes actionable code.

Requires:
    GITHUB_TOKEN   in backend/.env  (ghp_... PAT with repo scope)
    GITHUB_OWNER   optional (default: leerobber)
    GITHUB_REPO    optional (default: GH05T3)
    GITHUB_BASE_BRANCH  optional (default: main)
"""
from __future__ import annotations

import hashlib
import logging
import os
import re
import time
from pathlib import Path

import httpx
from dotenv import load_dotenv

load_dotenv(Path(__file__).parents[1] / ".env")

LOG = logging.getLogger("ghost.evolution.auto_pr")

_OWNER  = os.environ.get("GITHUB_OWNER", "leerobber")
_REPO   = os.environ.get("GITHUB_REPO",  "GH05T3")
_BASE   = os.environ.get("GITHUB_BASE_BRANCH", "main")

_IMPL_TEMPLATE = '''\
"""Auto-generated skeleton from SAGE elite proposal #{cycle_id}.

Proposal: {proposal}

Score: {score} | Agent: {agent_id} | Timestamp: {timestamp}

TODO: Implement the proposal above.
"""
# Place your implementation here.
'''


def _slugify(text: str, max_len: int = 40) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug[:max_len]


async def create_proposal_pr(
    proposal: str,
    score: float,
    cycle_id: int,
    agent_id: str = "unknown",
    *,
    dry_run: bool = False,
) -> dict:
    """Create a draft GitHub PR with an implementation skeleton.

    Returns a dict with {ok, pr_url, error}.
    Designed to be called fire-and-forget from kairos.record_cycle.
    """
    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN") or ""
    if not token:
        LOG.debug("[auto_pr] GITHUB_TOKEN not set — skipping PR creation")
        return {"ok": False, "error": "GITHUB_TOKEN not set"}

    slug = _slugify(proposal[:50])
    uid  = hashlib.md5(f"{cycle_id}{proposal[:30]}".encode()).hexdigest()[:6]
    branch_name = f"sage/proposal-{cycle_id}-{slug}-{uid}"
    timestamp = time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime())

    skeleton_content = _IMPL_TEMPLATE.format(
        cycle_id=cycle_id,
        proposal=proposal,
        score=round(score, 3),
        agent_id=agent_id,
        timestamp=timestamp,
    )
    file_path = f"backend/evolution/proposals/proposal_{cycle_id:04d}_{uid}.py"

    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    if dry_run:
        LOG.info("[auto_pr] dry_run — would create branch=%s file=%s", branch_name, file_path)
        return {"ok": True, "dry_run": True, "branch": branch_name, "file": file_path}

    api = f"https://api.github.com/repos/{_OWNER}/{_REPO}"

    async with httpx.AsyncClient(timeout=15.0, headers=headers) as c:
        # 1. Get base branch SHA
        r = await c.get(f"{api}/git/ref/heads/{_BASE}")
        if r.status_code != 200:
            err = f"could not get base branch SHA: {r.status_code}"
            LOG.warning("[auto_pr] %s", err)
            return {"ok": False, "error": err}
        base_sha = r.json()["object"]["sha"]

        # 2. Create branch
        r = await c.post(f"{api}/git/refs", json={
            "ref": f"refs/heads/{branch_name}",
            "sha": base_sha,
        })
        if r.status_code not in {200, 201, 422}:
            err = f"branch creation failed: {r.status_code} {r.text[:120]}"
            LOG.warning("[auto_pr] %s", err)
            return {"ok": False, "error": err}

        # 3. Create file
        import base64
        encoded = base64.b64encode(skeleton_content.encode()).decode()
        r = await c.put(f"{api}/contents/{file_path}", json={
            "message": f"[SAGE] Skeleton for proposal #{cycle_id}: {proposal[:60]}",
            "content": encoded,
            "branch":  branch_name,
        })
        if r.status_code not in {200, 201}:
            err = f"file creation failed: {r.status_code} {r.text[:120]}"
            LOG.warning("[auto_pr] %s", err)
            return {"ok": False, "error": err}

        # 4. Create draft PR
        pr_body = (
            f"## SAGE Elite Proposal — Cycle #{cycle_id}\n\n"
            f"**Score:** {round(score, 3)} | **Agent:** `{agent_id}`\n\n"
            f"### Proposal\n> {proposal}\n\n"
            f"### Implementation Checklist\n"
            f"- [ ] Review the proposal above\n"
            f"- [ ] Implement in the skeleton file `{file_path}`\n"
            f"- [ ] Add tests\n"
            f"- [ ] Update `CLAUDE.md` if this changes architecture\n\n"
            f"_Auto-generated by KAIROS at {timestamp}_"
        )
        r = await c.post(f"{api}/pulls", json={
            "title": f"[SAGE] {proposal[:72]}",
            "body":  pr_body,
            "head":  branch_name,
            "base":  _BASE,
            "draft": True,
        })
        if r.status_code not in {200, 201}:
            err = f"PR creation failed: {r.status_code} {r.text[:200]}"
            LOG.warning("[auto_pr] %s", err)
            return {"ok": False, "error": err}

        pr_url = r.json().get("html_url", "")
        LOG.info("[auto_pr] Created draft PR: %s", pr_url)
        return {"ok": True, "pr_url": pr_url, "branch": branch_name}
